app_root:
    path: /
    defaults: {_controller: Dream89AppBundle:Home:index}

user_register:
    path: /register
    defaults: {_controller: Dream89AppBundle:User:register}

user_create:
    path: /user/create
    defaults: {_controller: Dream89AppBundle:User:register}
    requirements: { _method: post }
